title: Blog
description: My Personal Blog
author: Ebru Gulec
github: https://github.com/ebrugulec
about: I'm a Software Engineer

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/glcebru"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/mwlite/in/glcebru"
    - icon: fa-github
      link: "https://github.com/ebrugulec"
    - icon: fa-youtube
      link: "https://www.youtube.com/channel/UC12ao9RgpXhO1VIiWF0jfdw"
    - icon: fa-glass-cheers
      link: "https://www.getrevue.co/profile/ebruguleceg"
    - icon: fa-goodreads
      link: "https://www.goodreads.com/user/show/83034282-ebru-gulec"

share:
  twitter_username: glcebru
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/

url: "https://gulecebru.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
